### ISSUE TITLE
Don't work in html files

### ISSUE THREAD

**Issue by 50l3r** [hwen/tag-wrapper#2]
I can't use this extension in html or php files.

When i press Ctrl+shift+i it dont do anything.

**Comment by hwen** [comment]
Default keybinging is `ctrl+i` 

Your can change it to `ctrl+shift+i` in vscode `keybindings.json` file by adding this code 
```
    {
        "key": "ctrl+shift+i",
        "command": "extension.wrapTag",
        "when": "editorTextFocus"
    }
```

**Comment by 50l3r** [comment]
Much thanks. Maybe the problem caused by vscode intellisense: https://github.com/Microsoft/vscode/issues/28417

**Comment by hwen** [comment]
Ohhhh, Thx for feedback~

I didn't
