### ISSUE TITLE
It only works on multiple lines?

### ISSUE THREAD

**Issue by aferreira44** [hwen/tag-wrapper#3]
Nothing happens when I select a piece of code inside a single line.
Working well on multiple lines.

Using Ubuntu 17.10, vscode 1.19.1 and pluggin version 0.2.3

Anybody can help me?

**Comment by hwen** [comment]
hi, It seem everything go well with my machine ( both single or multiple line

my env:
- Ubuntu 16.4
- vscode 1.19.1
- pluggin 0.2.3

Are you using mac ?

may be you can change your keybindings following [here](https://github.com/hwen/tag-wrapper/issues/2)
