### ISSUE TITLE
Doesn't work, doesn't throw error

### ISSUE THREAD

**Issue by selfagency** [hwen/tag-wrapper#8]
I can confirm the plugin is installed, activated, and has a key binding but when I hit `ctrl-I`, nothing happens and no errors are thrown in the developer tools console.

**Comment by cognominal** [comment]
Same here. On Mac, both on monoline or multilines selection.
See #4

**Comment by yugen** [comment]
+1

**Comment by Alecto** [comment]
+1

**Comment by selfagency** [comment]
closing this because it's 2 years old, this project is defunct, and i want to clean up my issues tab
